// Code generated by protoc-gen-go. DO NOT EDIT.
// source: messages/devices.proto

package devices

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateDeviceRequest struct {
	DeviceSerial         string   `protobuf:"bytes,1,opt,name=device_serial,json=deviceSerial,proto3" json:"device_serial,omitempty"`
	PhoneNumber          string   `protobuf:"bytes,2,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateDeviceRequest) Reset()         { *m = CreateDeviceRequest{} }
func (m *CreateDeviceRequest) String() string { return proto.CompactTextString(m) }
func (*CreateDeviceRequest) ProtoMessage()    {}
func (*CreateDeviceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e6f974e263b75e9b, []int{0}
}

func (m *CreateDeviceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateDeviceRequest.Unmarshal(m, b)
}
func (m *CreateDeviceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateDeviceRequest.Marshal(b, m, deterministic)
}
func (m *CreateDeviceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateDeviceRequest.Merge(m, src)
}
func (m *CreateDeviceRequest) XXX_Size() int {
	return xxx_messageInfo_CreateDeviceRequest.Size(m)
}
func (m *CreateDeviceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateDeviceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateDeviceRequest proto.InternalMessageInfo

func (m *CreateDeviceRequest) GetDeviceSerial() string {
	if m != nil {
		return m.DeviceSerial
	}
	return ""
}

func (m *CreateDeviceRequest) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

type CreateDeviceResponse struct {
	DeviceId             uint32   `protobuf:"varint,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateDeviceResponse) Reset()         { *m = CreateDeviceResponse{} }
func (m *CreateDeviceResponse) String() string { return proto.CompactTextString(m) }
func (*CreateDeviceResponse) ProtoMessage()    {}
func (*CreateDeviceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e6f974e263b75e9b, []int{1}
}

func (m *CreateDeviceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateDeviceResponse.Unmarshal(m, b)
}
func (m *CreateDeviceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateDeviceResponse.Marshal(b, m, deterministic)
}
func (m *CreateDeviceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateDeviceResponse.Merge(m, src)
}
func (m *CreateDeviceResponse) XXX_Size() int {
	return xxx_messageInfo_CreateDeviceResponse.Size(m)
}
func (m *CreateDeviceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateDeviceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateDeviceResponse proto.InternalMessageInfo

func (m *CreateDeviceResponse) GetDeviceId() uint32 {
	if m != nil {
		return m.DeviceId
	}
	return 0
}

func init() {
	proto.RegisterType((*CreateDeviceRequest)(nil), "messages.devices.CreateDeviceRequest")
	proto.RegisterType((*CreateDeviceResponse)(nil), "messages.devices.CreateDeviceResponse")
}

func init() { proto.RegisterFile("messages/devices.proto", fileDescriptor_e6f974e263b75e9b) }

var fileDescriptor_e6f974e263b75e9b = []byte{
	// 179 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0xcb, 0x4d, 0x2d, 0x2e,
	0x4e, 0x4c, 0x4f, 0x2d, 0xd6, 0x4f, 0x49, 0x2d, 0xcb, 0x4c, 0x4e, 0x2d, 0xd6, 0x2b, 0x28, 0xca,
	0x2f, 0xc9, 0x17, 0x12, 0x80, 0x89, 0xeb, 0x41, 0xc5, 0x95, 0x62, 0xb9, 0x84, 0x9d, 0x8b, 0x52,
	0x13, 0x4b, 0x52, 0x5d, 0xc0, 0x02, 0x41, 0xa9, 0x85, 0xa5, 0xa9, 0xc5, 0x25, 0x42, 0xca, 0x5c,
	0xbc, 0x10, 0x15, 0xf1, 0xc5, 0xa9, 0x45, 0x99, 0x89, 0x39, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x9c,
	0x41, 0x3c, 0x10, 0xc1, 0x60, 0xb0, 0x98, 0x90, 0x22, 0x17, 0x4f, 0x41, 0x46, 0x7e, 0x5e, 0x6a,
	0x7c, 0x5e, 0x69, 0x6e, 0x52, 0x6a, 0x91, 0x04, 0x13, 0x58, 0x0d, 0x37, 0x58, 0xcc, 0x0f, 0x2c,
	0xa4, 0x64, 0xcc, 0x25, 0x82, 0x6a, 0x7c, 0x71, 0x41, 0x7e, 0x5e, 0x71, 0xaa, 0x90, 0x34, 0x17,
	0x27, 0xd4, 0xfc, 0xcc, 0x14, 0xb0, 0xd9, 0xbc, 0x41, 0x1c, 0x10, 0x01, 0xcf, 0x14, 0x27, 0xc5,
	0x28, 0xf9, 0xb4, 0xc4, 0xa2, 0x5c, 0xfd, 0xe2, 0xa2, 0x64, 0x7d, 0xb0, 0xbb, 0xf5, 0xd1, 0xbd,
	0x93, 0xc4, 0x06, 0x16, 0x37, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0xf1, 0xed, 0x88, 0x3f, 0xe9,
	0x00, 0x00, 0x00,
}
