// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.6.1
// source: messages/log.proto

package log

import (
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DeviceLog struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DeviceTime *timestamp.Timestamp `protobuf:"bytes,1,opt,name=device_time,json=deviceTime,proto3" json:"device_time,omitempty"`
	ServerTime *timestamp.Timestamp `protobuf:"bytes,2,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"`
	Humidity   uint32               `protobuf:"varint,3,opt,name=humidity,proto3" json:"humidity,omitempty"`
}

func (x *DeviceLog) Reset() {
	*x = DeviceLog{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_log_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeviceLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceLog) ProtoMessage() {}

func (x *DeviceLog) ProtoReflect() protoreflect.Message {
	mi := &file_messages_log_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceLog.ProtoReflect.Descriptor instead.
func (*DeviceLog) Descriptor() ([]byte, []int) {
	return file_messages_log_proto_rawDescGZIP(), []int{0}
}

func (x *DeviceLog) GetDeviceTime() *timestamp.Timestamp {
	if x != nil {
		return x.DeviceTime
	}
	return nil
}

func (x *DeviceLog) GetServerTime() *timestamp.Timestamp {
	if x != nil {
		return x.ServerTime
	}
	return nil
}

func (x *DeviceLog) GetHumidity() uint32 {
	if x != nil {
		return x.Humidity
	}
	return 0
}

type DeviceDataFrame struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DeviceId     uint32       `protobuf:"varint,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	DeviceSerial string       `protobuf:"bytes,2,opt,name=device_serial,json=deviceSerial,proto3" json:"device_serial,omitempty"`
	DeviceLogs   []*DeviceLog `protobuf:"bytes,3,rep,name=device_logs,json=deviceLogs,proto3" json:"device_logs,omitempty"`
}

func (x *DeviceDataFrame) Reset() {
	*x = DeviceDataFrame{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_log_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeviceDataFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceDataFrame) ProtoMessage() {}

func (x *DeviceDataFrame) ProtoReflect() protoreflect.Message {
	mi := &file_messages_log_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceDataFrame.ProtoReflect.Descriptor instead.
func (*DeviceDataFrame) Descriptor() ([]byte, []int) {
	return file_messages_log_proto_rawDescGZIP(), []int{1}
}

func (x *DeviceDataFrame) GetDeviceId() uint32 {
	if x != nil {
		return x.DeviceId
	}
	return 0
}

func (x *DeviceDataFrame) GetDeviceSerial() string {
	if x != nil {
		return x.DeviceSerial
	}
	return ""
}

func (x *DeviceDataFrame) GetDeviceLogs() []*DeviceLog {
	if x != nil {
		return x.DeviceLogs
	}
	return nil
}

type GetDeviceDataFrameBySerialRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DeviceSerial string               `protobuf:"bytes,1,opt,name=device_serial,json=deviceSerial,proto3" json:"device_serial,omitempty"`
	StartDate    *timestamp.Timestamp `protobuf:"bytes,2,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate      *timestamp.Timestamp `protobuf:"bytes,3,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	Step         uint32               `protobuf:"varint,4,opt,name=step,proto3" json:"step,omitempty"`
}

func (x *GetDeviceDataFrameBySerialRequest) Reset() {
	*x = GetDeviceDataFrameBySerialRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_log_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDeviceDataFrameBySerialRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeviceDataFrameBySerialRequest) ProtoMessage() {}

func (x *GetDeviceDataFrameBySerialRequest) ProtoReflect() protoreflect.Message {
	mi := &file_messages_log_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeviceDataFrameBySerialRequest.ProtoReflect.Descriptor instead.
func (*GetDeviceDataFrameBySerialRequest) Descriptor() ([]byte, []int) {
	return file_messages_log_proto_rawDescGZIP(), []int{2}
}

func (x *GetDeviceDataFrameBySerialRequest) GetDeviceSerial() string {
	if x != nil {
		return x.DeviceSerial
	}
	return ""
}

func (x *GetDeviceDataFrameBySerialRequest) GetStartDate() *timestamp.Timestamp {
	if x != nil {
		return x.StartDate
	}
	return nil
}

func (x *GetDeviceDataFrameBySerialRequest) GetEndDate() *timestamp.Timestamp {
	if x != nil {
		return x.EndDate
	}
	return nil
}

func (x *GetDeviceDataFrameBySerialRequest) GetStep() uint32 {
	if x != nil {
		return x.Step
	}
	return 0
}

type GetDeviceDataFrameByIdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DeviceId  uint32               `protobuf:"varint,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	StartDate *timestamp.Timestamp `protobuf:"bytes,2,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate   *timestamp.Timestamp `protobuf:"bytes,3,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	Step      uint32               `protobuf:"varint,4,opt,name=step,proto3" json:"step,omitempty"`
}

func (x *GetDeviceDataFrameByIdRequest) Reset() {
	*x = GetDeviceDataFrameByIdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_log_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDeviceDataFrameByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeviceDataFrameByIdRequest) ProtoMessage() {}

func (x *GetDeviceDataFrameByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_messages_log_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeviceDataFrameByIdRequest.ProtoReflect.Descriptor instead.
func (*GetDeviceDataFrameByIdRequest) Descriptor() ([]byte, []int) {
	return file_messages_log_proto_rawDescGZIP(), []int{3}
}

func (x *GetDeviceDataFrameByIdRequest) GetDeviceId() uint32 {
	if x != nil {
		return x.DeviceId
	}
	return 0
}

func (x *GetDeviceDataFrameByIdRequest) GetStartDate() *timestamp.Timestamp {
	if x != nil {
		return x.StartDate
	}
	return nil
}

func (x *GetDeviceDataFrameByIdRequest) GetEndDate() *timestamp.Timestamp {
	if x != nil {
		return x.EndDate
	}
	return nil
}

func (x *GetDeviceDataFrameByIdRequest) GetStep() uint32 {
	if x != nil {
		return x.Step
	}
	return 0
}

type WaterLog struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           uint32               `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	DeviceSerial string               `protobuf:"bytes,2,opt,name=device_serial,json=deviceSerial,proto3" json:"device_serial,omitempty"`
	Username     string               `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	EntryTime    *timestamp.Timestamp `protobuf:"bytes,4,opt,name=entry_time,json=entryTime,proto3" json:"entry_time,omitempty"`
	Volume       uint32               `protobuf:"varint,5,opt,name=volume,proto3" json:"volume,omitempty"`
}

func (x *WaterLog) Reset() {
	*x = WaterLog{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_log_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WaterLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WaterLog) ProtoMessage() {}

func (x *WaterLog) ProtoReflect() protoreflect.Message {
	mi := &file_messages_log_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WaterLog.ProtoReflect.Descriptor instead.
func (*WaterLog) Descriptor() ([]byte, []int) {
	return file_messages_log_proto_rawDescGZIP(), []int{4}
}

func (x *WaterLog) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *WaterLog) GetDeviceSerial() string {
	if x != nil {
		return x.DeviceSerial
	}
	return ""
}

func (x *WaterLog) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *WaterLog) GetEntryTime() *timestamp.Timestamp {
	if x != nil {
		return x.EntryTime
	}
	return nil
}

func (x *WaterLog) GetVolume() uint32 {
	if x != nil {
		return x.Volume
	}
	return 0
}

type CreateWaterLogBySerialRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DeviceSerial string               `protobuf:"bytes,1,opt,name=device_serial,json=deviceSerial,proto3" json:"device_serial,omitempty"`
	EntryTime    *timestamp.Timestamp `protobuf:"bytes,2,opt,name=entry_time,json=entryTime,proto3" json:"entry_time,omitempty"`
	Volume       uint32               `protobuf:"varint,3,opt,name=volume,proto3" json:"volume,omitempty"`
}

func (x *CreateWaterLogBySerialRequest) Reset() {
	*x = CreateWaterLogBySerialRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_log_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateWaterLogBySerialRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWaterLogBySerialRequest) ProtoMessage() {}

func (x *CreateWaterLogBySerialRequest) ProtoReflect() protoreflect.Message {
	mi := &file_messages_log_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWaterLogBySerialRequest.ProtoReflect.Descriptor instead.
func (*CreateWaterLogBySerialRequest) Descriptor() ([]byte, []int) {
	return file_messages_log_proto_rawDescGZIP(), []int{5}
}

func (x *CreateWaterLogBySerialRequest) GetDeviceSerial() string {
	if x != nil {
		return x.DeviceSerial
	}
	return ""
}

func (x *CreateWaterLogBySerialRequest) GetEntryTime() *timestamp.Timestamp {
	if x != nil {
		return x.EntryTime
	}
	return nil
}

func (x *CreateWaterLogBySerialRequest) GetVolume() uint32 {
	if x != nil {
		return x.Volume
	}
	return 0
}

type CreateWaterLogByDeviceIdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DeviceId  uint32               `protobuf:"varint,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	EntryTime *timestamp.Timestamp `protobuf:"bytes,2,opt,name=entry_time,json=entryTime,proto3" json:"entry_time,omitempty"`
	Volume    uint32               `protobuf:"varint,3,opt,name=volume,proto3" json:"volume,omitempty"`
}

func (x *CreateWaterLogByDeviceIdRequest) Reset() {
	*x = CreateWaterLogByDeviceIdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_log_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateWaterLogByDeviceIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWaterLogByDeviceIdRequest) ProtoMessage() {}

func (x *CreateWaterLogByDeviceIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_messages_log_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWaterLogByDeviceIdRequest.ProtoReflect.Descriptor instead.
func (*CreateWaterLogByDeviceIdRequest) Descriptor() ([]byte, []int) {
	return file_messages_log_proto_rawDescGZIP(), []int{6}
}

func (x *CreateWaterLogByDeviceIdRequest) GetDeviceId() uint32 {
	if x != nil {
		return x.DeviceId
	}
	return 0
}

func (x *CreateWaterLogByDeviceIdRequest) GetEntryTime() *timestamp.Timestamp {
	if x != nil {
		return x.EntryTime
	}
	return nil
}

func (x *CreateWaterLogByDeviceIdRequest) GetVolume() uint32 {
	if x != nil {
		return x.Volume
	}
	return 0
}

type GetWaterLogsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WaterLogs []*WaterLog `protobuf:"bytes,1,rep,name=water_logs,json=waterLogs,proto3" json:"water_logs,omitempty"`
	FarmId    uint32      `protobuf:"varint,2,opt,name=farm_id,json=farmId,proto3" json:"farm_id,omitempty"`
}

func (x *GetWaterLogsResponse) Reset() {
	*x = GetWaterLogsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_log_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetWaterLogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWaterLogsResponse) ProtoMessage() {}

func (x *GetWaterLogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_messages_log_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWaterLogsResponse.ProtoReflect.Descriptor instead.
func (*GetWaterLogsResponse) Descriptor() ([]byte, []int) {
	return file_messages_log_proto_rawDescGZIP(), []int{7}
}

func (x *GetWaterLogsResponse) GetWaterLogs() []*WaterLog {
	if x != nil {
		return x.WaterLogs
	}
	return nil
}

func (x *GetWaterLogsResponse) GetFarmId() uint32 {
	if x != nil {
		return x.FarmId
	}
	return 0
}

var File_messages_log_proto protoreflect.FileDescriptor

var file_messages_log_proto_rawDesc = []byte{
	0x0a, 0x12, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2f, 0x6c, 0x6f, 0x67, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x6c,
	0x6f, 0x67, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0xa1, 0x01, 0x0a, 0x09, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x4c, 0x6f,
	0x67, 0x12, 0x3b, 0x0a, 0x0b, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x74, 0x69, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x52, 0x0a, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x3b,
	0x0a, 0x0b, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52,
	0x0a, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x68,
	0x75, 0x6d, 0x69, 0x64, 0x69, 0x74, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x68,
	0x75, 0x6d, 0x69, 0x64, 0x69, 0x74, 0x79, 0x22, 0x8d, 0x01, 0x0a, 0x0f, 0x44, 0x65, 0x76, 0x69,
	0x63, 0x65, 0x44, 0x61, 0x74, 0x61, 0x46, 0x72, 0x61, 0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x64,
	0x65, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08,
	0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x64, 0x12, 0x23, 0x0a, 0x0d, 0x64, 0x65, 0x76, 0x69,
	0x63, 0x65, 0x5f, 0x73, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0c, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x53, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x12, 0x38, 0x0a,
	0x0b, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x6c, 0x6f, 0x67, 0x73, 0x18, 0x03, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x17, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x6c, 0x6f,
	0x67, 0x2e, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x4c, 0x6f, 0x67, 0x52, 0x0a, 0x64, 0x65, 0x76,
	0x69, 0x63, 0x65, 0x4c, 0x6f, 0x67, 0x73, 0x22, 0xce, 0x01, 0x0a, 0x21, 0x47, 0x65, 0x74, 0x44,
	0x65, 0x76, 0x69, 0x63, 0x65, 0x44, 0x61, 0x74, 0x61, 0x46, 0x72, 0x61, 0x6d, 0x65, 0x42, 0x79,
	0x53, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x23, 0x0a,
	0x0d, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x73, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x53, 0x65, 0x72, 0x69,
	0x61, 0x6c, 0x12, 0x39, 0x0a, 0x0a, 0x73, 0x74, 0x61, 0x72, 0x74, 0x5f, 0x64, 0x61, 0x74, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x52, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x44, 0x61, 0x74, 0x65, 0x12, 0x35, 0x0a,
	0x08, 0x65, 0x6e, 0x64, 0x5f, 0x64, 0x61, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x07, 0x65, 0x6e, 0x64,
	0x44, 0x61, 0x74, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x74, 0x65, 0x70, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x04, 0x73, 0x74, 0x65, 0x70, 0x22, 0xc2, 0x01, 0x0a, 0x1d, 0x47, 0x65, 0x74,
	0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x44, 0x61, 0x74, 0x61, 0x46, 0x72, 0x61, 0x6d, 0x65, 0x42,
	0x79, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x64, 0x65,
	0x76, 0x69, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x64,
	0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x64, 0x12, 0x39, 0x0a, 0x0a, 0x73, 0x74, 0x61, 0x72, 0x74,
	0x5f, 0x64, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x44, 0x61,
	0x74, 0x65, 0x12, 0x35, 0x0a, 0x08, 0x65, 0x6e, 0x64, 0x5f, 0x64, 0x61, 0x74, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x52, 0x07, 0x65, 0x6e, 0x64, 0x44, 0x61, 0x74, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x74, 0x65,
	0x70, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x73, 0x74, 0x65, 0x70, 0x22, 0xae, 0x01,
	0x0a, 0x08, 0x57, 0x61, 0x74, 0x65, 0x72, 0x4c, 0x6f, 0x67, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x12, 0x23, 0x0a, 0x0d, 0x64, 0x65,
	0x76, 0x69, 0x63, 0x65, 0x5f, 0x73, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0c, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x53, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x12,
	0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x39, 0x0a, 0x0a, 0x65,
	0x6e, 0x74, 0x72, 0x79, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x65, 0x6e, 0x74,
	0x72, 0x79, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x76, 0x6f, 0x6c, 0x75, 0x6d, 0x65,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x76, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x22, 0x97,
	0x01, 0x0a, 0x1d, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x57, 0x61, 0x74, 0x65, 0x72, 0x4c, 0x6f,
	0x67, 0x42, 0x79, 0x53, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x23, 0x0a, 0x0d, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x73, 0x65, 0x72, 0x69, 0x61,
	0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x53,
	0x65, 0x72, 0x69, 0x61, 0x6c, 0x12, 0x39, 0x0a, 0x0a, 0x65, 0x6e, 0x74, 0x72, 0x79, 0x5f, 0x74,
	0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x65, 0x6e, 0x74, 0x72, 0x79, 0x54, 0x69, 0x6d, 0x65,
	0x12, 0x16, 0x0a, 0x06, 0x76, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x06, 0x76, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x22, 0x91, 0x01, 0x0a, 0x1f, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x57, 0x61, 0x74, 0x65, 0x72, 0x4c, 0x6f, 0x67, 0x42, 0x79, 0x44, 0x65, 0x76,
	0x69, 0x63, 0x65, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09,
	0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x08, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x64, 0x12, 0x39, 0x0a, 0x0a, 0x65, 0x6e, 0x74,
	0x72, 0x79, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x65, 0x6e, 0x74, 0x72, 0x79,
	0x54, 0x69, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x76, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x76, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x22, 0x66, 0x0a, 0x14,
	0x47, 0x65, 0x74, 0x57, 0x61, 0x74, 0x65, 0x72, 0x4c, 0x6f, 0x67, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x35, 0x0a, 0x0a, 0x77, 0x61, 0x74, 0x65, 0x72, 0x5f, 0x6c, 0x6f,
	0x67, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x73, 0x2e, 0x6c, 0x6f, 0x67, 0x2e, 0x57, 0x61, 0x74, 0x65, 0x72, 0x4c, 0x6f, 0x67,
	0x52, 0x09, 0x77, 0x61, 0x74, 0x65, 0x72, 0x4c, 0x6f, 0x67, 0x73, 0x12, 0x17, 0x0a, 0x07, 0x66,
	0x61, 0x72, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x66, 0x61,
	0x72, 0x6d, 0x49, 0x64, 0x42, 0x1d, 0x5a, 0x1b, 0x66, 0x61, 0x72, 0x6d, 0x2f, 0x73, 0x72, 0x63,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2f,
	0x6c, 0x6f, 0x67, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_messages_log_proto_rawDescOnce sync.Once
	file_messages_log_proto_rawDescData = file_messages_log_proto_rawDesc
)

func file_messages_log_proto_rawDescGZIP() []byte {
	file_messages_log_proto_rawDescOnce.Do(func() {
		file_messages_log_proto_rawDescData = protoimpl.X.CompressGZIP(file_messages_log_proto_rawDescData)
	})
	return file_messages_log_proto_rawDescData
}

var file_messages_log_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_messages_log_proto_goTypes = []interface{}{
	(*DeviceLog)(nil),                         // 0: messages.log.DeviceLog
	(*DeviceDataFrame)(nil),                   // 1: messages.log.DeviceDataFrame
	(*GetDeviceDataFrameBySerialRequest)(nil), // 2: messages.log.GetDeviceDataFrameBySerialRequest
	(*GetDeviceDataFrameByIdRequest)(nil),     // 3: messages.log.GetDeviceDataFrameByIdRequest
	(*WaterLog)(nil),                          // 4: messages.log.WaterLog
	(*CreateWaterLogBySerialRequest)(nil),     // 5: messages.log.CreateWaterLogBySerialRequest
	(*CreateWaterLogByDeviceIdRequest)(nil),   // 6: messages.log.CreateWaterLogByDeviceIdRequest
	(*GetWaterLogsResponse)(nil),              // 7: messages.log.GetWaterLogsResponse
	(*timestamp.Timestamp)(nil),               // 8: google.protobuf.Timestamp
}
var file_messages_log_proto_depIdxs = []int32{
	8,  // 0: messages.log.DeviceLog.device_time:type_name -> google.protobuf.Timestamp
	8,  // 1: messages.log.DeviceLog.server_time:type_name -> google.protobuf.Timestamp
	0,  // 2: messages.log.DeviceDataFrame.device_logs:type_name -> messages.log.DeviceLog
	8,  // 3: messages.log.GetDeviceDataFrameBySerialRequest.start_date:type_name -> google.protobuf.Timestamp
	8,  // 4: messages.log.GetDeviceDataFrameBySerialRequest.end_date:type_name -> google.protobuf.Timestamp
	8,  // 5: messages.log.GetDeviceDataFrameByIdRequest.start_date:type_name -> google.protobuf.Timestamp
	8,  // 6: messages.log.GetDeviceDataFrameByIdRequest.end_date:type_name -> google.protobuf.Timestamp
	8,  // 7: messages.log.WaterLog.entry_time:type_name -> google.protobuf.Timestamp
	8,  // 8: messages.log.CreateWaterLogBySerialRequest.entry_time:type_name -> google.protobuf.Timestamp
	8,  // 9: messages.log.CreateWaterLogByDeviceIdRequest.entry_time:type_name -> google.protobuf.Timestamp
	4,  // 10: messages.log.GetWaterLogsResponse.water_logs:type_name -> messages.log.WaterLog
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_messages_log_proto_init() }
func file_messages_log_proto_init() {
	if File_messages_log_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_messages_log_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeviceLog); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_log_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeviceDataFrame); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_log_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDeviceDataFrameBySerialRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_log_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDeviceDataFrameByIdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_log_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WaterLog); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_log_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateWaterLogBySerialRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_log_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateWaterLogByDeviceIdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_log_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetWaterLogsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_messages_log_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_messages_log_proto_goTypes,
		DependencyIndexes: file_messages_log_proto_depIdxs,
		MessageInfos:      file_messages_log_proto_msgTypes,
	}.Build()
	File_messages_log_proto = out.File
	file_messages_log_proto_rawDesc = nil
	file_messages_log_proto_goTypes = nil
	file_messages_log_proto_depIdxs = nil
}
