
up:
	docker-compose -f docker-compose.yml up -d

down:
	docker-compose -f docker-compose.yml down

backup:
	mkdir backup
	bash backup.sh

backup-cronjob:
	bash setup_cronjob.sh


setup:
	bash setup.sh
