version: '3.8'

services:
    postgres:
        container_name: postgres
        image: postgres
        environment:
            POSTGRES_USER: asap
            POSTGRES_HOST: localhost
            POSTGRES_PASSWORD: asapDB!
            

        ports:
            - 5432:5432
        volumes:
            - ./data/postgres:/var/lib/postgresql/data
        restart: always
       

    pgadmin4:
        container_name: pgadmin4
        image: dpage/pgadmin4
        environment:
            PGADMIN_DEFAULT_EMAIL: asap@carriot.ir
            PGADMIN_DEFAULT_PASSWORD: asapDB!)
        depends_on: 
            - postgres
        ports:
            - 5050:80
        restart: always 
        
    