server:
  host: 0.0.0.0
  grpcport: 7777
  httpport: 8000

database:
  host: localhost
  port: 5432
  user: asap
  password: asapDB!
  db: farmdb
  connMaxLifetime: 0
  maxIdleConns: 20
  maxOpenConns: 20

credential:
  tokensecret: secret

